### ISSUE TITLE
gen.p.values computes one-sided pvalues but in rgauss setting mu can be <0

### ISSUE THREAD

**Issue by durandg12** [sanssouci-org/sanssouci#88]
gen.p.values should maybe compute two-sided pvalues, or, for replicability and retro-compatibility, we should make a second function computing 2-sided pvalues

**Comment by durandg12** [comment]
Better, add a new `mode` argument which computes one-sided pvalues if `mode==1` or `mode=="one-sided"` and two-sided pvalues if `mode==2` or `mode=="two-sided"`, the default being `"one-sided"` for retro-compatibility.

**Comment by pneuvial** [comment]
For consistency wrt classical testing functions in R we should use `alternative = c("two.sided", "less", "greater")`

**Comment by durandg12** [comment]
> For consistency wrt classical testing functions in R we should use `alternative = c("two.sided", "less", "greater")`

But shouldn't the default for our function be the "historical" greater one-sided option instead of two.sided? (still for compatibility reasons) ?

**Comment by pneuvial** [comment]
> > For consistency wrt classical testing functions in R we should use `alternative = c("two.sided", "less", "greater")`
> 
> But shouldn't the default for our function be the "historical" greater one-sided option instead of two.sided? (still for compatibility reasons) ?

There is a tension between maintaining compatibility and bringing consistency wrt common practice in base R or other packages. Here I'd recommend to use classical "two.sided" as the default.  This will require to track the use of this function in the package and in our simulation scripts in order to explicitly force "greater" where that was the intended choice.

**Comment by durandg12** [comment]
Ok, this is what I have implemented today, as you can see in the commit
